#!/usr/bin/env bash
set -euo pipefail

EXECUTE=0
FROM_GATEWAY="mtt2"
CHECK_GATEWAY="sipnet2"
DESTINATION="74953206510"
CALLER_ID="74951341045"
TIMEOUT="45"
APP="&echo()"
UUID="$(cat /proc/sys/kernel/random/uuid)"

usage() {
  cat <<'USAGE'
Usage: fs_test_call_mtt_to_sipnet.sh [--execute] [options]

Places the Dotochki carrier-loop test call from MTT to the SIPNET DID.
Dry-run is the default; pass --execute to originate a live call.

Options:
  --execute              Run the originate command.
  --from-gateway NAME    Outbound gateway, default: mtt2.
  --check-gateway NAME   Return-route gateway to verify, default: sipnet2.
  --destination NUMBER   Destination number, default: 74953206510.
  --caller-id NUMBER     Caller ID, default: 74951341045.
  --timeout SECONDS      Originate and call timeout, default: 45.
  --uuid UUID            Origination UUID. Generated by default.
  --app APP              FreeSWITCH app after answer, default: &echo().
  -h, --help             Show this help.
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --execute) EXECUTE=1; shift ;;
    --from-gateway) FROM_GATEWAY="${2:?}"; shift 2 ;;
    --check-gateway) CHECK_GATEWAY="${2:?}"; shift 2 ;;
    --destination) DESTINATION="${2:?}"; shift 2 ;;
    --caller-id) CALLER_ID="${2:?}"; shift 2 ;;
    --timeout) TIMEOUT="${2:?}"; shift 2 ;;
    --uuid) UUID="${2:?}"; shift 2 ;;
    --app) APP="${2:?}"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown argument: $1" >&2; usage >&2; exit 2 ;;
  esac
done

ORIGINATE="originate {ignore_early_media=true,origination_uuid=${UUID},origination_caller_id_number=${CALLER_ID},caller_id_number=${CALLER_ID},effective_caller_id_number=${CALLER_ID},absolute_codec_string=PCMA,PCMU,originate_timeout=${TIMEOUT},call_timeout=${TIMEOUT},sip_cid_type=none,rtp_secure_media=false}sofia/gateway/${FROM_GATEWAY}/${DESTINATION} ${APP}"

echo "Checking FreeSWITCH status and gateways..."
fs_cli -x 'status'
fs_cli -x 'show calls'
fs_cli -x "sofia status gateway ${FROM_GATEWAY}"
fs_cli -x "sofia status gateway ${CHECK_GATEWAY}"
echo
echo "Origination UUID: ${UUID}"
echo "Command: fs_cli -x \"${ORIGINATE}\""

if [[ "${EXECUTE}" != "1" ]]; then
  echo "Dry-run only. Re-run with --execute to place the live test call."
  exit 0
fi

echo "Placing live carrier-loop test call..."
fs_cli -x "${ORIGINATE}"

cat <<EOF

Post-call verification:
  grep ${UUID} /var/log/freeswitch/freeswitch.log /var/log/freeswitch/freeswitch.log.1
  tail -n 8 /var/log/freeswitch/cdr-csv/Master.csv
  grep -E '${UUID}|finish_call_ok|archive_metadata_ok' /var/log/freeswitch/pbx-recording-finalizer.log
EOF